builds:
  - main: ./cmd/ox/main.go
    binary: ox
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
archives:
  - name_template: >-
      ox_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else if eq .Arch "darwin" }}Darwin
      {{- else if eq .Arch "linux" }}Linux
      {{- else if eq .Arch "linux" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}_{{- .Mips }}{{ end }}
checksum:
  name_template: checksums.txt
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'