name: Tests
on: [push]
jobs:
  lint:
    name: GolangCI Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.1"
      
  tests-off:
    name: ${{matrix.os}} - Go v${{matrix.go-version}} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: 
          - '1.18.x'
          - '1.19.x'
        os: 
          - 'macos-latest'
          - 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          
      - name: Test
        run: go test -tags sqlite -cover  ./...    
      
      # - name: Integration Tests
      #   run: go test -tags "sqlite,integration" -cover  ./cli/... 